import Navbar from "@/app/(components)/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "BBS - client",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="">
          <Navbar />
          <div className="flex justify-center items-center p-10">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
